ec2:
  imageId: ami-0f3a440bbcff3d043
  instance-type: t2.micro
  max-count: 1
  min-count: 1
  security-group: MosaicUserAdd
  ebs-optimized: false
  user_tag:
    - "sudo apt update"
    - "sudo apt install -y awscli"
    - "(%time%) echo %user_id% 님의 새로운 파일인 %file_name% 을 다운로드 합니다"
    - "aws s3 cp s3://%bucket_name%/%user_id%/'%file_name%' /home/ubuntu/'%file_name%'"
    - "다운로드 완료"

