ec2:
  imageId: ami-0f3a440bbcff3d043
  instanceType: t2.micro
  maxCount: 1
  minCount: 1
  securityGroup: MosaicUserAdd
  ebsOptimized: false
  userTag:
    - "sudo apt update"
    - "sudo apt install -y awscli"
    - "(%time%) echo %user_id% 님의 새로운 파일인 %file_name% 을 다운로드 합니다"
    - "aws s3 cp s3://%bucket_name%/%user_id%/'%file_name%' /home/ubuntu/'%file_name%'"
    - "다운로드 완료"

